Clinic/Models/DoctorViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Medcare.Models
{
    public class CreateWorkdayViewModel
    {
        [Display(Name = "Day of week")]
        [Required]
        public DayOfWeek Day { get; set; }

        [Display(Name = "Start hour")]
        [RegularExpression(@"^(0[0-9]|1[0-9]|2[1-3]):[0|3][0]$", ErrorMessage = "Invalid hour format. Please use hh:00 or hh:30.")]
        [Required]
        public string StartHour { get; set; }

        [Display(Name = "End hour")]
        [RegularExpression(@"^(0[0-9]|1[0-9]|2[1-3]):[0|3][0]$", ErrorMessage = "Invalid hour format. Please use hh:00 or hh:30.")]
        [Required]
        public string EndHour { get; set; }

        [Required]
        public IEnumerable<SelectListItem> ClinicsList { get; set; }
    }
}

Clinic/Controllers/DoctorsController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DoctorsController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var roleId = RoleManager.FindByName("Doctor").Id;
            return View(await UserManager.Users.Where(u => u.Roles.Select(r => r.RoleId).Contains(roleId)).ToListAsync());
        }

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterDoctorViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { FirstName = userViewModel.FirstName, LastName = userViewModel.LastName, PWZ = userViewModel.PWZ, UserName = userViewModel.Email, Email = userViewModel.Email, IsConfirmed = true };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                if (adminresult.Succeeded)
                {
                    var result = await UserManager.AddToRoleAsync(user.Id, "Doctor");
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("", result.Errors.First());
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult AssignClinics(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = UserManager.FindById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(new AssignClinicsViewModel()
            {
                DoctorId = id,
                DoctorName = user.Name,
                ClinicsList = db.Clinics.ToList().Select(x => new SelectListItem()
                {
                    Selected = db.DoctorsToClinics.Where(y => y.DoctorId == id).Where(y => y.ClinicId == x.Id).Any(),
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignClinics(AssignClinicsViewModel model, params string[] selectedClinic)
        {
            // removing currently existing assignments
            db.DoctorsToClinics.RemoveRange(db.DoctorsToClinics.Where(y => y.DoctorId == model.DoctorId));
            if (selectedClinic != null)
            {
                foreach (var item in selectedClinic)
                {
                    db.DoctorsToClinics.Add(new Medcare.Models.DoctorToClinic() { Id = Guid.NewGuid(), DoctorId = model.DoctorId, ClinicId = new Guid(item) });
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        #region Helpers
        private ApplicationDbContext db = new ApplicationDbContext();
        public DoctorsController()
        {
        }
        public DoctorsController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        #endregion
    }
}

Clinic/Views/Doctors/AssignClinics.cshtml
@model IdentitySample.Models.AssignClinicsViewModel

@{
    ViewBag.Title = "Assign clinics";
}

<h2>@ViewBag.Title</h2>
<h4>Choose clinics where <mark>@Model.DoctorName</mark> works</h4>
<hr />

@using (Html.BeginForm("AssignClinics", "Doctors", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DoctorId)


    <dl class="dl-horizontal">
        <dt>Select clinics</dt>
        <dd>
            @foreach (var item in Model.ClinicsList)
            {
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="SelectedClinic" value="@item.Value" checked="@item.Selected">
                        @item.Text
                    </label>
                </div>
            }
        </dd>
        <dt></dt>
        <dd>
            <input type="submit" value="Assign" class="btn btn-default" />
        </dd>
    </dl>
}

<div>
    @Html.ActionLink("Go back", "Index")
</div>

Clinic/Views/Doctors/Create.cshtml
@model IdentitySample.Models.RegisterDoctorViewModel
@{
    ViewBag.Title = "Add new doctor";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Doctors", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new doctor account</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PWZ, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PWZ, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PWZ, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}
<div>
    @Html.ActionLink("Go back", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinic/Views/Doctors/Delete.cshtml
@model IdentitySample.Models.ApplicationUser

@{
    ViewBag.Title = "Delete doctor";
}

<h2>@ViewBag.Title</h2>
<h4>Are you sure you want to delete <mark>@Html.DisplayFor(model => model.Name)</mark>?</h4>
<hr />
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <dl class="dl-horizontal">
        <dt>Doctor name</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>
        <dd><br /><input type="submit" value="Delete" class="btn btn-danger" /></dd>
    </dl>
    
}
<div>
    @Html.ActionLink("Go back", "Index")
</div>

Clinic/Views/Doctors/Edit.cshtml
@model IdentitySample.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit.</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit User Form.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
               @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Roles", new { @class = "control-label col-md-2" })
            <span class=" col-md-10">
                @foreach (var item in Model.RolesList)
                {
                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @Html.Label(item.Value, new { @class = "control-label" })
                }
            </span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinic/Views/Doctors/Index.cshtml
@model IEnumerable<IdentitySample.Models.ApplicationUser>

@{
    ViewBag.Title = "Doctors list";
}

<h2>@ViewBag.Title</h2>
<h4>View, manage and assign doctors to clinics</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PWZ)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PWZ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Assign clinics", "AssignClinics", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Add new doctor", "Create", null, new { @class = "btn btn-default btn-primary" })
</p>